### ISSUE TITLE
Add new readme files for Curl 7.78 & 7.79 wrt OpenSSL 3.0 & 1.1 builds 

### ISSUE THREAD

**Issue by the4amfriend** [ituglib/readme_files#2]
Curl versions 7.78 & 7.79 were missing readme files for both OpenSSL 3.1 & 1.1 builds.

**Comment by rsbeckerca** [comment]
Associated with https://github.com/ituglib/ituglib-build/issues/14

**Comment by rsbeckerca** [comment]
Readme files have been added. They were missing. Referenced in the Curl_Deploy `jenkinsfile` at
https://github.com/ituglib/ituglib-build/blob/01bbf5268d61dcaaad3b1b8c9f2b93a541b6d18c/Jenkinsfile.deploy.curl#L64
and
https://github.com/ituglib/ituglib-build/blob/01bbf5268d61dcaaad3b1b8c9f2b93a541b6d18c/Jenkinsfile.deploy.curl#L86

**Note:** The changes must be made in the Jenkins job. Copies in the above lines are captured and pasted into the files in that repo manually as a backup.
